# Generated by Django 4.0.4 on 2022-04-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircrafts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, verbose_name='номер места')),
                ('fare_conditions', models.CharField(max_length=100, verbose_name='условия тарифа')),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='aircrafts.aircraft', verbose_name='Код воздушного судна')),
            ],
        ),
    ]
