# Generated by Django 4.0.4 on 2022-04-29 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=9, unique=True, verbose_name='Номер билета')),
                ('contact_data', models.TextField(max_length=100)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking', verbose_name='номер брони')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='пассажир с id')),
                ('passenger_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.profile', verbose_name='Профиль пассажира')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['ticket_number'],
            },
        ),
    ]
