# Generated by Django 3.2.9 on 2021-11-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_code', models.CharField(max_length=6, unique=True, verbose_name='Код воздушного судна')),
                ('model', models.CharField(max_length=10, verbose_name='Модель воздушного судна')),
                ('range', models.CharField(max_length=10, verbose_name='ранг')),
            ],
        ),
    ]
