# Generated by Django 3.2.9 on 2021-11-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.UUIDField(verbose_name='Аэропорт')),
                ('airport_name', models.CharField(max_length=100, verbose_name='Имя аэропорта')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('coordinates', models.CharField(max_length=100, verbose_name='Координаты аэропорта')),
                ('timezone', models.CharField(max_length=100, verbose_name='Часовой пояс')),
            ],
        ),
    ]
