# Generated by Django 3.2.9 on 2021-11-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport_code',
            field=models.UUIDField(verbose_name='Код аэропорта'),
        ),
    ]
