# Generated by Django 4.0.4 on 2022-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_ref', models.CharField(max_length=9, verbose_name='номер брони')),
                ('book_date', models.DateTimeField(auto_now_add=True, verbose_name='дата бронирования')),
                ('total_amount', models.FloatField(verbose_name='Итоговая цена')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
