# Generated by Django 4.0.4 on 2022-04-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '__first__'),
        ('seats', '__first__'),
        ('tickets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_number', models.CharField(max_length=10, verbose_name='Номер посадочного талона')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardingpasses', to='flights.flight', verbose_name='Рейс')),
                ('seat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardingpasses', to='seats.seat', verbose_name='Номер места')),
                ('ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardingpasses', to='tickets.ticket', verbose_name='Номер билета')),
            ],
            options={
                'db_table': 'boardingpasses',
            },
        ),
    ]
