# Generated by Django 4.0.4 on 2022-04-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        ('tickets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.CharField(max_length=100, verbose_name='Условия тарифа')),
                ('amount', models.CharField(max_length=10, verbose_name='Количество')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketflights', to='flights.flight', verbose_name='Рейс')),
                ('ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketflights', to='tickets.ticket', verbose_name='Номер билета')),
            ],
        ),
    ]
